"use client";
import { createContext, useContext, useEffect, useRef, useState, type ReactNode } from "react";
import { X, Plus } from "lucide-react";
const CloseContext = createContext<() => void>(() => {});
export const useCloseModal = () => useContext(CloseContext);
export function Modal({open,onClose,title,children,busy=false,wide=false}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;busy?:boolean;wide?:boolean}) {
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current;if(!d)return;if(open&&!d.open)d.showModal();if(!open&&d.open)d.close();},[open]);
 useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[open]);
 return <dialog ref={ref} className={`app-dialog ${wide?'wide':''}`} aria-label={title} onCancel={e=>{e.preventDefault();if(!busy)onClose();}} onPointerDown={e=>{if(e.target===e.currentTarget&&!busy){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><CloseContext.Provider value={onClose}><header className="app-dialog-header"><h2>{title}</h2><button type="button" aria-label="Close dialog" disabled={busy} onClick={onClose}><X size={19}/></button></header>{open&&<div className="app-dialog-body">{children}</div>}</CloseContext.Provider></dialog>;
}
export function ModalTrigger({title,label,children,wide=false}:{title:string;label?:string;children:ReactNode;wide?:boolean}){const[open,setOpen]=useState(false);return <><button className="action-launch" onClick={()=>setOpen(true)}><Plus size={15}/>{label||title}</button><Modal title={title} open={open} onClose={()=>setOpen(false)} wide={wide}>{children}</Modal></>;}
type PromptField={name:string;label:string;type?:string;value?:string;max?:number;options?:Array<{value:string;label:string}>};
export function useEntryDialog(){const [entry,setEntry]=useState<{title:string;fields:PromptField[];resolve:(v:Record<string,string>|null)=>void}|null>(null);const requestEntry=(title:string,fields:PromptField[])=>new Promise<Record<string,string>|null>(resolve=>setEntry({title,fields,resolve}));function close(){entry?.resolve(null);setEntry(null);}const dialog=<Modal open={!!entry} onClose={close} title={entry?.title||''}><form className="entry-dialog-form" onSubmit={e=>{e.preventDefault();entry?.resolve(Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>);setEntry(null);}}>{entry?.fields.map(f=><label key={f.name}>{f.label}{f.options?<select name={f.name} defaultValue={f.value}>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input name={f.name} type={f.type||'text'} defaultValue={f.value} max={f.max} minLength={f.type==='password'?8:undefined} step={f.type==='number'?'any':undefined} required autoComplete="off"/>}</label>)}<footer><button type="button" onClick={close}>Cancel</button><button className="ops-primary">Save</button></footer></form></Modal>;return {requestEntry,dialog};}
