'use client';
import {useState} from 'react';
import {Modal} from './Modal';
import {readJson} from '../lib/http';
import type {Review,ReviewLine} from '../lib/operations/documents';
type Component={id:string;name:string;sku:string;unit:string};
type PO={id:string;po_number:string;supplier_name:string};
type POLine={id:string;purchase_order_id:string;component_id:string;component_name:string;purchase_unit:string;ordered_quantity:number;received_quantity:number;unit_cost:number;invoiced_quantity?:number};
export default function ProcurementPdf({kind,components,vendors,pos,poLines,onSaved,preview=false}:{kind:'po'|'invoice';components:Component[];vendors:{id:string;name:string}[];pos:PO[];poLines:POLine[];onSaved:()=>Promise<void>;preview?:boolean}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[text,setText]=useState(''),[warning,setWarning]=useState(''),[extracted,setExtracted]=useState(false),[result,setResult]=useState('');
 const initial=():Review=>({kind,number:'',date:new Date().toISOString().slice(0,10),vendorId:'',poId:'',amount:'0',lines:[]});
 const [review,setReview]=useState<Review>(initial);
 const patch=(i:number,b:Partial<ReviewLine>)=>setReview(r=>({...r,lines:r.lines.map((l,j)=>i===j?{...l,...b,checked:b.checked??false}:l)}));
 const available=poLines.filter(l=>l.purchase_order_id===review.poId);
 async function extract(f:File){setBusy(true);setError('');setExtracted(false);setFile(f);try{const form=new FormData();form.set('file',f);const data=await readJson<{lines:ReviewLine[];text:string;warning:string}>(await fetch('/api/inventory/documents',{method:'POST',body:form}));setText(data.text);setWarning(data.warning);setReview(r=>({...r,lines:data.lines.map(l=>{const normalized=l.description.toLowerCase().trim();const c=components.find(c=>c.name.toLowerCase()===normalized || c.sku.toLowerCase()===normalized);return {...l,componentId:c?.id||'',lineId:'',checked:false};})}));setExtracted(true);}catch(e){setError(e instanceof Error?e.message:'PDF extraction failed');}finally{setBusy(false);}}
 async function save(){if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.set('file',file);form.set('review',JSON.stringify(review));const r=await readJson<{status:string;comparisons:{description:string;flags:string[]}[]}>(await fetch('/api/inventory/documents',{method:'POST',body:form}));setResult(r.status==='review_required'?'Invoice saved. Review flagged quantity, receiving or price differences.':kind==='po'?'Purchase order created.':'Invoice saved and matched.');await onSaved();setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Could not save document');}finally{setBusy(false);}}
 return <><button className="action-launch" onClick={()=>{setReview(initial());setFile(null);setExtracted(false);setError('');setOpen(true);}}>+ Import {kind==='po'?'PO':'invoice'} PDF</button>{result&&<p role="status">{result}</p>}<Modal title={kind==='po'?'Import purchase order':'Import & match invoice'} open={open} onClose={()=>setOpen(false)} busy={busy} wide><form className="ops-form" onSubmit={e=>{e.preventDefault();void save();}}>
 <label>PDF · up to 4 MB<input type="file" accept="application/pdf,.pdf" disabled={busy||preview} onChange={e=>{const f=e.target.files?.[0];if(f)void extract(f);}}/></label>
 {busy&&<p role="status">Processing…</p>}{error&&<p className="ops-error" role="alert">{error}</p>}
 {extracted&&<><p>{warning}</p><details><summary>Extracted document text</summary><pre style={{whiteSpace:'pre-wrap',maxHeight:220,overflow:'auto'}}>{text||'No readable text'}</pre></details>
 <div className="ops-fields"><label>{kind==='po'?'PO number':'Invoice number'}<input required value={review.number} onChange={e=>setReview({...review,number:e.target.value})}/></label><label>Date<input required type="date" value={review.date} onChange={e=>setReview({...review,date:e.target.value})}/></label>
 {kind==='po'?<><label>Vendor<select required value={review.vendorId} onChange={e=>setReview({...review,vendorId:e.target.value})}><option value="">Select vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Vendor order number<input value={review.vendorNumber||''} onChange={e=>setReview({...review,vendorNumber:e.target.value})}/></label></>:<><label>Purchase order<select required value={review.poId} onChange={e=>setReview({...review,poId:e.target.value,lines:review.lines.map(l=>({...l,lineId:'',checked:false}))})}><option value="">Select PO</option>{pos.map(p=><option key={p.id} value={p.id}>{p.po_number} · {p.supplier_name}</option>)}</select></label><label>Invoice total ₹ (including taxes)<input required type="number" min="0" step="0.01" value={review.amount} onChange={e=>setReview({...review,amount:e.target.value})}/></label></>}
 </div><div className="ops-lines"><header><strong>Review line items</strong><button type="button" disabled={review.lines.length>=100} onClick={()=>setReview({...review,lines:[...review.lines,{description:'',quantity:'',cost:'0',unit:'unit',componentId:'',lineId:'',checked:false}]})}>+ Add item</button></header>
 {review.lines.map((l,i)=>{const matched=available.find(p=>p.id===l.lineId);return <fieldset key={i} style={{border:'1px solid var(--border, #344454)',borderRadius:10,padding:14,margin:'12px 0'}}><legend>Item {i+1}</legend><div className="ops-fields"><label>Description<input required value={l.description} onChange={e=>patch(i,{description:e.target.value})}/></label><label>{kind==='po'?'Stock component':'Matching PO item'}<select required value={kind==='po'?l.componentId:l.lineId} onChange={e=>patch(i,kind==='po'?{componentId:e.target.value}:{lineId:e.target.value})}><option value="">Select item</option>{kind==='po'?components.map(c=><option key={c.id} value={c.id}>{c.name} ({c.unit})</option>):available.map(p=><option key={p.id} value={p.id}>{p.component_name} · {p.purchase_unit}</option>)}</select></label><label>Quantity<input required type="number" min="0.000001" step="any" value={l.quantity} onChange={e=>patch(i,{quantity:e.target.value})}/></label><label>Unit<select value={l.unit} onChange={e=>patch(i,{unit:e.target.value})}>{['unit','g','kg','pack',...components.map(c=>c.unit)].filter((v,i,a)=>a.indexOf(v)===i).map(u=><option key={u}>{u}</option>)}</select></label><label>Unit price ₹<input required type="number" min="0" step="any" value={l.cost} onChange={e=>patch(i,{cost:e.target.value})}/></label></div>
 {matched&&<p>Ordered: {matched.ordered_quantity} · Received: {matched.received_quantity} · Previously invoiced: {matched.invoiced_quantity||0} {matched.purchase_unit} · PO unit price: ₹{matched.unit_cost}</p>}
 <label><input type="checkbox" required checked={l.checked} onChange={e=>patch(i,{checked:e.target.checked})}/> Checked against PDF</label><button type="button" onClick={()=>setReview({...review,lines:review.lines.filter((_,j)=>i!==j)})}>Remove item</button></fieldset>;})}</div>
 <button className="ops-primary" disabled={busy||!review.lines.length}>{kind==='po'?'Create purchase order':'Save & compare invoice'}</button></>}
 </form></Modal></>;
}
