"use client";
import {useState} from 'react';
import {Modal} from './Modal';
const labels={vendorName:'Vendor name',vendorCompany:'Vendor company',vendorAddress:'Vendor address',vendorPhone:'Vendor phone',vendorGstin:'Vendor GSTIN',companyName:'Billing company',billingAddress:'Billing address',gstin:'Billing GSTIN',deliveryAddress:'Delivery address',contactPerson:'Contact person',paymentTerms:'Payment terms',paymentMethod:'Payment method',advancePayment:'Advance payment',conditions:'Terms & conditions',preparedBy:'Prepared by',approvedBy:'Approved by'};
type Details=Record<keyof typeof labels,string>;
const blank:Details={vendorName:'',vendorCompany:'',vendorAddress:'',vendorPhone:'',vendorGstin:'',companyName:'SATMI',billingAddress:'',gstin:'',deliveryAddress:'',contactPerson:'',paymentTerms:'',paymentMethod:'ONLINE',advancePayment:'',conditions:'Goods must match the specifications mentioned in this PO.\nAny damaged or incorrect items must be replaced by the vendor.\nInvoice should mention the PO Number.\nPayment will be processed as per the agreed payment terms after receipt and verification of goods.',preparedBy:'',approvedBy:''};
export default function PurchaseOrderForm({vendors,components,onSave,busy}:{vendors:Array<{id:string;name:string;phone:string;tax_id:string;address:string}>;components:Array<{id:string;name:string;unit:string}>;onSave:(b:Record<string,unknown>)=>Promise<boolean>;busy:boolean}) {
 const [open,setOpen]=useState(false),[details,setDetails]=useState(blank),[vendorId,setVendorId]=useState('');
 const [lines,setLines]=useState([{componentId:'',description:'',quantity:'',unit:'unit',cost:'',gst:'0'}]);
 const total=lines.reduce((sum,l)=>sum+Math.round(Number(l.quantity)*Number(l.cost)*(1+Number(l.gst)/100)*100)/100,0);
 return <><a className="action-launch" href="/po-template.xlsx" download>Download Excel template</a><button className="action-launch" onClick={()=>setOpen(true)}>+ Create purchase order</button><Modal title="Create purchase order" open={open} onClose={()=>setOpen(false)} busy={busy} wide><form className="ops-form" onSubmit={async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));if(await onSave({...values,vendorId,details,lines}))setOpen(false);}}>
 <div className="ops-fields"><label>Registered vendor<select required value={vendorId} onChange={e=>{setVendorId(e.target.value);const v=vendors.find(v=>v.id===e.target.value);if(v)setDetails(d=>({...d,vendorName:v.name,vendorCompany:v.name,vendorAddress:v.address||'',vendorPhone:v.phone||'',vendorGstin:v.tax_id||''}));}}><option value="">Select vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>PO number<input name="number" required/></label><label>PO date<input name="date" type="date" required defaultValue={new Date().toLocaleDateString('en-CA')}/></label><label>Expected delivery<input name="expected" type="date" required/></label></div>
 <div className="ops-fields">{Object.entries(labels).map(([key,label])=><label key={key}>{label}{/Address|conditions/.test(key)?<textarea required value={details[key as keyof Details]} onChange={e=>setDetails({...details,[key]:e.target.value})}/>:<input required value={details[key as keyof Details]} onChange={e=>setDetails({...details,[key]:e.target.value})}/>}</label>)}</div>
 <div className="po-entry-table"><table><thead><tr><th>Component</th><th>Item description</th><th>Qty</th><th>Unit</th><th>Unit price</th><th>GST %</th><th>Total</th><th/></tr></thead><tbody>{lines.map((line,index)=><tr key={index}><td><select required value={line.componentId} onChange={e=>{const c=components.find(c=>c.id===e.target.value);setLines(lines.map((l,i)=>i===index?{...l,componentId:e.target.value,description:c?.name||'',unit:c?.unit||'unit'}:l));}}><option value="">Choose</option>{components.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></td>{(['description','quantity','unit','cost','gst'] as const).map(key=><td key={key}>{key==='unit'?<select value={line.unit} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,unit:e.target.value}:l))}>{['unit','kg','g','pack'].map(u=><option key={u}>{u}</option>)}</select>:<input aria-label={`${key} row ${index+1}`} required type={key==='description'?'text':'number'} min={key==='quantity'?'0.001':'0'} max={key==='gst'?'100':undefined} step="any" value={line[key]} onChange={e=>setLines(lines.map((l,i)=>i===index?{...l,[key]:e.target.value}:l))}/>}</td>)}<td>{(Number(line.quantity)*Number(line.cost)*(1+Number(line.gst)/100)).toLocaleString('en-IN',{maximumFractionDigits:2})}</td><td><button type="button" disabled={lines.length===1} onClick={()=>setLines(lines.filter((_,i)=>i!==index))}>Remove</button></td></tr>)}</tbody></table></div>
 <button type="button" onClick={()=>setLines([...lines,{componentId:'',description:'',quantity:'',unit:'unit',cost:'',gst:'0'}])}>Add row</button><p><strong>Grand total: {total.toLocaleString('en-IN',{maximumFractionDigits:2})}</strong></p><button className="ops-primary" disabled={busy}>{busy?'Saving…':'Save purchase order'}</button><p>Open the saved PO and choose Download PDF. All entered fields are preserved.</p>
 </form></Modal></>;
}
