// Read-only provider checks. Never logs credentials, tokens or customer records.
import postgres from 'postgres';
import {writeFile} from 'node:fs/promises';
const report:Record<string,unknown>={checkedAt:new Date().toISOString(),authentication:{url:!!process.env.NEXT_PUBLIC_SUPABASE_URL,publishableKey:!!process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,adminKey:!!process.env.SUPABASE_SERVICE_ROLE_KEY},shopify:{domain:!!(process.env.SHOPIFY_SHOP_DOMAIN||process.env.SHOPIFY_STORE_DOMAIN),token:!!process.env.SHOPIFY_ADMIN_ACCESS_TOKEN}};
const db=postgres(process.env.SUPABASE_DB_URL||'',{max:1,connect_timeout:8,onnotice:()=>{}});
try{const rows=await db`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE status='OUT FOR DELIVERY') current_ofd FROM orders`;report.database={accessible:true,...rows[0]};}catch(e){report.database={accessible:false,code:(e as {code?:string}).code,error:e instanceof Error?e.message:'Unavailable'};}finally{await db.end();}
if(process.env.SHIPROCKET_EMAIL&&process.env.SHIPROCKET_PASSWORD){try{const res=await fetch('https://apiv2.shiprocket.in/v1/external/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:process.env.SHIPROCKET_EMAIL,password:process.env.SHIPROCKET_PASSWORD}),signal:AbortSignal.timeout(20000)});const json=await res.json();report.shiprocket={authStatus:res.status,authenticated:!!json.token};if(json.token){const params=new URLSearchParams({per_page:'100',page:'1',sort:'DESC',sort_by:'id',channel_id:process.env.SHIPROCKET_CHANNEL_ID||''});const orders=await fetch('https://apiv2.shiprocket.in/v1/external/orders?'+params,{headers:{Authorization:'Bearer '+json.token},signal:AbortSignal.timeout(20000)});const d=await orders.json();report.shiprocket={...report.shiprocket as object,ordersStatus:orders.status,sampleCount:d.data?.length||0,statusCounts:(d.data||[]).reduce((a:Record<string,number>,o:{status:string})=>{a[o.status]=(a[o.status]||0)+1;return a;},{})};}}catch{report.shiprocket={error:'Provider check failed or timed out'};}}
if(process.env.SHOPIFY_SHOP_DOMAIN&&process.env.SHOPIFY_ADMIN_ACCESS_TOKEN){try{const r=await fetch(`https://${process.env.SHOPIFY_SHOP_DOMAIN}/admin/api/${process.env.SHOPIFY_API_VERSION||'2026-04'}/graphql.json`,{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Access-Token':process.env.SHOPIFY_ADMIN_ACCESS_TOKEN},body:JSON.stringify({query:'{ shop { id } }'}),signal:AbortSignal.timeout(15000)});const d=await r.json();report.shopify={...report.shopify as object,status:r.status,verified:!!d.data?.shop?.id};}catch{report.shopify={...report.shopify as object,verified:false};}}
await writeFile('docs/connection-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
